characters = [
        {
            "index": 0,
            "class": "scouter",
            "ilvl-endless": 1415,
            "ilvl-aor": 1415,
            "spring": False,
            "bleak": False,
            "lopang": False,
            "guildDonation": True,
            "rapport": False,
        },
        {
            "index": 1,
            "class": "sorceress",
            "ilvl-endless": 1445,
            "ilvl-aor": 1445,
            "spring": False,
            "bleak": False,
            "lopang": False,
            "guildDonation": True,
            "rapport": False,
        },
        {
            "index": 2,
            "class": "sorceress",
            "ilvl-endless": 1540,
            "ilvl-aor": 1540,
            "spring": False,
            "bleak": False,
            "lopang": False,
            "guildDonation": True,
            "rapport": False,
        },
        {
            "index": 3,
            "class": "sorceress",
            "ilvl-endless": 1600,
            "ilvl-aor": 1600,
            "spring": False,
            "bleak": False,
            "lopang": False,
            "guildDonation": True,
            "rapport": False,
        },
        {
            "index": 4,
            "class": "sorceress",
            "ilvl-endless": 1415,
            "ilvl-aor": 1415,
            "spring": False,
            "bleak": False,
            "lopang": False,
            "guildDonation": True,
            "rapport": False,
        },
        {
            "index": 5,
            "class": "sorceress",
            "ilvl-endless": 1540,
            "ilvl-aor": 1540,
            "spring": False,
            "bleak": False,
            "lopang": False,
            "guildDonation": True,
            "rapport": False,
        },
        {
            "index": 6,
            "class": "summoner",
            "ilvl-endless": 1580,
            "ilvl-aor": 1580,
            "spring": False,
            "bleak": False,
            "lopang": False,
            "guildDonation": True,
            "rapport": False,
        },
        {
            "index": 7,
            "class": "bard",
            "ilvl-endless": 1490,
            "ilvl-aor": 1490,
            "spring": False,
            "bleak": False,
            "lopang": False,
            "guildDonation": True,
            "rapport": False,
        },
        {
            "index": 8,
            "class": "paladin",
            "ilvl-endless": 1415,
            "ilvl-aor": 1415,
            "spring": False,
            "bleak": False,
            "lopang": False,
            "guildDonation": True,
            "rapport": False,
        },
        {
            "index": 9,
            "class": "slayer",
            "ilvl-endless": 1490,
            "ilvl-aor": 1490,
            "spring": False,
            "bleak": False,
            "lopang": False,
            "guildDonation": True,
            "rapport": False,
        },
        {
            "index": 10,
            "class": "slayer",
            "ilvl-endless": 1490,
            "ilvl-aor": 1490,
            "spring": False,
            "bleak": False,
            "lopang": False,
            "guildDonation": True,
            "rapport": False,
        },
        {
            "index": 11,
            "class": "sharpshooter",
            "ilvl-endless": 1415,
            "ilvl-aor": 1415,
            "spring": False,
            "bleak": False,
            "lopang": False,
            "guildDonation": True,
            "rapport": False,
        },
        {
            "index": 12,
            "class": "slayer",
            "ilvl-endless": 1580,
            "ilvl-aor": 1580,
            "spring": False,
            "bleak": False,
            "lopang": False,
            "guildDonation": True,
            "rapport": False,
        },
]
